apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: charts-markdownlint
  annotations:
    # -- Ref. <https://pipelinesascode.com/docs/guide/authoringprs>
    pipelinesascode.tekton.dev/on-cel-expression: |
      ( event == "pull_request" || ( event == "push" && source_branch == "main") ) && body.sender.login != "livewyer-bot"
    pipelinesascode.tekton.dev/on-target-branch: "[main]"
spec:
  pipelineRef:
    resolver: cluster
    params:
      - name: kind
        value: pipeline
      - name: name
        value: markdownlint
  params:
    - name: repo_name
      value: "{{repo_name}}"
    - name: source_branch
      value: "{{source_branch}}"
  taskRunTemplate:
    serviceAccountName: pipelines-as-code-runner
    podTemplate:
      securityContext:
        fsGroup: 65532
  workspaces:
    - name: source
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 128Mi
