apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: charts-markdownlint
  annotations:
    # -- Ref. <https://pipelinesascode.com/docs/guide/authoringprs>
    pipelinesascode.tekton.dev/on-cel-expression: |
      ( event == "pull_request" || ( event == "push" && source_branch == "main") ) && body.sender.login != "livewyer-bot"
spec:
  pipelineRef:
    resolver: cluster
    params:
      - name: kind
        value: pipeline
      - name: name
        value: markdownlint
  params:
    - name: url
      value: "{{repo_url}}"
    - name: revision
      value: "{{revision}}"
    - name: fileName
      value: "Chart.yaml"
  taskRunTemplate:
    serviceAccountName: pipelines-as-code-runner
    podTemplate:
      securityContext:
        fsGroup: 65532
  workspaces:
    - name: source
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 128Mi
    - name: basic-auth
      secret:
        secretName: "{{git_auth_secret}}"
